// Generated by scripts/api-contract.py from FastAPI OpenAPI.
export type AnalyzeRequest = { question?: string };
export type Answer = {
  status: "answered" | "insufficient_evidence";
  claims: Array<Claim>;
  proposed_note?: string | null;
};
export type AuditResponse = {
  event: string;
  proposal_id: string;
  created_at: string;
};
export type Citation = { source_id: string; quote: string };
export type Claim = { text: string; citations: Array<Citation> };
export type DecisionRequest = { decision: "approve" | "reject" };
export type DecisionResponse = {
  status: "applied" | "rejected";
  note_id: string | null;
  replayed: boolean;
};
export type HTTPValidationError = { detail?: Array<ValidationError> };
export type NoteResponse = { id: string; content: string; created_at: string };
export type ProposalResponse = {
  id: string;
  content: string;
  content_hash: string;
  status: "pending" | "applied" | "rejected";
  expires_at: string;
  expected_version: number;
};
export type RunResponse = {
  id: string;
  ticket_id: string;
  ticket_version: number;
  status: "running" | "complete" | "failed";
  mode: "simulated" | "live";
  result: Answer | null;
  proposal: ProposalResponse | null;
  evidence: Array<SourceResponse>;
  trace: Record<string, unknown>;
  error_code: string | null;
  created_at: string;
};
export type RunSummary = {
  id: string;
  status: string;
  mode: string;
  created_at: string;
};
export type SessionResponse = {
  token: string;
  expires_at: string;
  mode: "simulated" | "live";
};
export type SourceResponse = {
  id: string;
  heading: string;
  body: string;
  title: string;
  source_id: string;
  version: number;
  status?: string;
};
export type TicketResponse = {
  id: string;
  sample: string;
  title: string;
  body: string;
  version: number;
  notes: Array<NoteResponse>;
  audit: Array<AuditResponse>;
  runs: Array<RunSummary>;
};
export type TicketSummary = {
  id: string;
  sample: string;
  title: string;
  body: string;
  version: number;
};
export type TicketsResponse = {
  tickets: Array<TicketSummary>;
  mode: "simulated" | "live";
};
export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
};
