"""Generate small TypeScript declarations from the actual FastAPI OpenAPI schema."""
import argparse
import json
import sys
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api"))
from main import app  # noqa: E402


def typescript(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(typescript(x) for x in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        if "properties" not in schema:
            return "Record<string, unknown>"
        required = schema.get("required", [])
        return "{ " + "; ".join(f"{k}{'' if k in required else '?'}: {typescript(v)}"
                                for k, v in schema["properties"].items()) + " }"
    return {"integer": "number", "number": "number", "string": "string",
            "boolean": "boolean", "null": "null"}.get(kind, "unknown")


parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
schema = app.openapi()
content = "// Generated by scripts/api-contract.py from FastAPI OpenAPI.\n"
content += "\n".join(f"export type {name} = {typescript(value)};" for name, value in
                     sorted(schema["components"]["schemas"].items())) + "\n"
content = subprocess.run(["node", str(ROOT / "node_modules/prettier/bin/prettier.cjs"),
                          "--parser", "typescript"], input=content, capture_output=True,
                         text=True, check=True).stdout
path = ROOT / "apps/web/lib/api-contract.ts"
if args.check:
    if path.read_text() != content:
        sys.exit("API contract drift; regenerate with scripts/api-contract.py")
else:
    path.write_text(content)
    (ROOT / "docs/openapi.json").write_text(json.dumps(schema, indent=2) + "\n")
