import base64
import json
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, TypeAdapter


class AudioFrame(BaseModel):
    """Audio frame containing base64-encoded linear PCM data."""

    type: Literal["audio"] = "audio"
    data: str = Field(description="Base64-encoded PCM bytes")
    sample_rate: int = Field(default=16000, description="Sample rate in Hz (e.g. 16000 or 24000)")
    channels: int = Field(default=1, description="Number of audio channels (1=mono)")
    format: str = Field(default="pcm_s16le", description="Audio format")

    def to_bytes(self) -> bytes:
        return base64.b64decode(self.data)

    @classmethod
    def from_bytes(
        cls, pcm: bytes, sample_rate: int = 16000, channels: int = 1
    ) -> "AudioFrame":
        return cls(
            data=base64.b64encode(pcm).decode("ascii"),
            sample_rate=sample_rate,
            channels=channels,
        )


class TranscriptEvent(BaseModel):
    """Transcription event representing spoken dialogue."""

    type: Literal["transcript"] = "transcript"
    role: Literal["user", "assistant", "model"]
    text: str
    is_final: bool = False


class CitationItem(BaseModel):
    """Individual citation representing evidence retrieved from the knowledge base."""

    source_id: str
    title: str = ""
    heading: str = ""
    quote: str = ""
    score: float | None = None
    status: str = "active"


class CitationEvent(BaseModel):
    """Citation event emitted to update UI citation cards in real time."""

    type: Literal["citation"] = "citation"
    citations: list[CitationItem] = Field(default_factory=list)


class ToolCallEvent(BaseModel):
    """Tool call invocation generated by the speech model."""

    type: Literal["tool_call"] = "tool_call"
    call_id: str
    name: str
    args: dict[str, Any] = Field(default_factory=dict)


class ToolResultEvent(BaseModel):
    """Result of a tool execution sent to model or client."""

    type: Literal["tool_result"] = "tool_result"
    call_id: str
    name: str
    result: dict[str, Any] = Field(default_factory=dict)


ControlAction = Literal["start", "stop", "interrupt", "turn_complete", "ping", "pong", "error"]


class ControlEvent(BaseModel):
    """Control event managing session lifecycle, turn boundaries, and interruptions."""

    type: Literal["control"] = "control"
    action: ControlAction
    message: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)


VoiceClientEvent = Annotated[
    AudioFrame | ControlEvent | ToolResultEvent | TranscriptEvent,
    Field(discriminator="type"),
]

VoiceServerEvent = Annotated[
    AudioFrame | TranscriptEvent | CitationEvent | ToolCallEvent | ToolResultEvent | ControlEvent,
    Field(discriminator="type"),
]

_client_adapter: TypeAdapter[VoiceClientEvent] = TypeAdapter(VoiceClientEvent)
_server_adapter: TypeAdapter[VoiceServerEvent] = TypeAdapter(VoiceServerEvent)


def parse_client_message(raw: str | bytes) -> VoiceClientEvent:
    """Parse incoming WebSocket message into a validated client event."""
    if isinstance(raw, bytes):
        return AudioFrame.from_bytes(raw)
    try:
        return _client_adapter.validate_json(raw)
    except Exception:
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, dict) and "type" in parsed:
                return _client_adapter.validate_python(parsed)
        except Exception:
            pass
        return TranscriptEvent(role="user", text=raw, is_final=True)


def parse_server_message(raw: str | bytes) -> VoiceServerEvent:
    """Parse incoming WebSocket message from the server into a validated server event."""
    if isinstance(raw, bytes):
        return AudioFrame.from_bytes(raw)
    try:
        return _server_adapter.validate_json(raw)
    except Exception:
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, dict) and "type" in parsed:
                return _server_adapter.validate_python(parsed)
        except Exception:
            pass
        return TranscriptEvent(role="assistant", text=raw, is_final=True)


def serialize_server_message(event: VoiceServerEvent) -> str:
    """Serialize server event to JSON string for WebSocket transmission."""
    return _server_adapter.dump_json(event).decode("utf-8")


def serialize_client_message(event: VoiceClientEvent) -> str:
    """Serialize client event to JSON string."""
    return _client_adapter.dump_json(event).decode("utf-8")
